### ISSUE TITLE
cant pull the code anymore

### ISSUE THREAD

**Issue by vadalus911** [davidbradway/myneurio#11]
git clone git@github.com:davidbradway/myneurio.git

Cloning into 'myneurio'...
The authenticity of host 'github.com (140.82.121.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by davidbradway** [comment]
try again
`git clone git@github.com:davidbradway/myneurio.git`

**Comment by vadalus911** [comment]
Hi,

Sorr still does not look to be working…


liam@hal:~$ git clone git@github.com:davidbradway/myneurio.git

Cloning into 'myneurio'...

git@github.com: Permission denied (publickey).

fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.

**Comment by davidbradway** [comment]
Try this
https://stackoverflow.com/a/2643584/4338646
